const NODE_ENV = process.env.NODE_ENV;
// frontend
const NEXT_PUBLIC_SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const NEXT_PUBLIC_SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
// backend
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const JWT_SECRET = process.env.JWT_SECRET;
const OPENAI_KEY = process.env.OPENAI_KEY;
const MDX_DOCS_PATH = process.env.MDX_DOCS_PATH;
const UPSTASH_REST_API_DOMAIN = process.env.UPSTASH_REST_API_DOMAIN;
const UPSTASH_REST_API_TOKEN = process.env.UPSTASH_REST_API_TOKEN;
const OPENAI_MODEL = process.env.OPENAI_MODEL;

export {
	NODE_ENV,
	NEXT_PUBLIC_SUPABASE_ANON_KEY,
	NEXT_PUBLIC_SUPABASE_URL,
	SUPABASE_SERVICE_ROLE_KEY,
	JWT_SECRET,
	OPENAI_KEY,
	MDX_DOCS_PATH,
	UPSTASH_REST_API_DOMAIN,
	UPSTASH_REST_API_TOKEN,
	OPENAI_MODEL,
};
